steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/meal-plan-service', '-f', 'lib/services/macro_genkit_service/Dockerfile', 'lib/services/macro_genkit_service']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/meal-plan-service']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'meal-plan-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/meal-plan-service'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'AIzaSyDIpeM_hJbv7dn3Nh_xIgQiCGOV6SvT7bw'

images:
  - 'gcr.io/$PROJECT_ID/meal-plan-service'