name: macro_calculator
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0 # Ensure consistent indentation

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1 # Use the latest stable version
  flutter_native_splash: ^2.4.5
  cupertino_icons: ^1.0.6
  flex_color_scheme: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#fc0330"
  image: assets/images/logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/ # Ensure this is indented by 2 spaces under 'flutter'

# This section should be at the root level (no indentation)


# Optional commented-out lines are fine
#  image_ios: assets/images/logo-ios.png
#  image_android: assets/images/logo-android.png
#  ios: true