name: macro_masher
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0 # Ensure consistent indentation

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1 # Use the latest stable version
  flutter_native_splash: ^2.4.5
  cupertino_icons: ^1.0.6
  flex_color_scheme: ^8.2.0
  flutter_riverpod: ^2.6.1
  http: ^1.3.0
  sqflite: ^2.4.2
  go_router: ^14.8.1
  path: ^1.9.1
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  riverpod: any
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_native_splash:
  color: "#FFFFFF"
  background_image: assets/images/foodbackground.png  # Use the food background
  image: assets/images/logo.png  # Keep the logo
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    image: assets/images/logo.png
    background_image: assets/images/foodbackground.png
  fullscreen: true
  android_gravity: center
  ios_content_mode: center
  web: false
  android_screen_orientation: portrait
  branding_mode: bottom

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png
  adaptive_icon_background: assets/images/foodbackground.png
  adaptive_icon_foreground: assets/images/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/ # Ensure this is indented by 2 spaces under 'flutter'