name: macro_masher
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0 # Ensure consistent indentation

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1 # Use the latest stable version
  flutter_native_splash: ^2.4.5
  cupertino_icons: ^1.0.6
  flex_color_scheme: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#000000"  # Dark background to complement the image
  background_image: assets/images/foodbackground.jpg  # Use the food background
  image: assets/images/logo.png  # Keep the logo
  android: true
  ios: true
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#fc0330"
  fullscreen: true
  android_gravity: center
  ios_content_mode: center
  web: false
  android_screen_orientation: portrait
  branding_mode: bottom

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png
  adaptive_icon_background: "#fc0330" # Same as splash screen color
  adaptive_icon_foreground: assets/images/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/ # Ensure this is indented by 2 spaces under 'flutter'